name: workflow1
on: [workflow_dispatch, push] 
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        run: |
              echo "Get repo url"
              echo "Clone repo"        
      - name: Get packages
        run: echo "Downloaded Packages"
      - name: Build Code
        run: echo "Code built"
  
